version: '3.9'

services:
  java-cass-exploration-app:
    image: nahwu2/cassandra-4-exploration:0.0.1
    restart: always
    ports:
      - 8002:8002
    depends_on:
      - "cassandra-db"
    environment:
      service_datastax_cassandra_node_contact_points: cassandra-db
      SERVICE_DATASTAX_CASSANDRA_NODE_PORT: 9042
      
  cassandra-db:
    image: cassandra:4.0.7
    restart: always
    ports:
      - 9042:9042
